---
abstract: 'List constants defined in a package'
author:
  - 'Jos Boumans <kane[at]cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Package-Constants
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: '0'
  perl: '5.006'
resources:
  repository: git://github.com/jib/package-constants.git
version: '0.06'
